"""empty message

Revision ID: 671ab50aaa1e
Revises: b588aaceb644
Create Date: 2021-02-01 11:17:32.628788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671ab50aaa1e'
down_revision = 'b588aaceb644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'artist_image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_image_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
