"""empty message

Revision ID: 9dd9ce3178b5
Revises: dcf4096db8d7
Create Date: 2021-02-03 12:52:31.825515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd9ce3178b5'
down_revision = 'dcf4096db8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Artist', 'website',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Venue', 'seeking_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('Venue', 'website',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('shows', 'artist_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('Venue', 'website',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('Venue', 'seeking_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Artist', 'website',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Artist', 'seeking_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
